# An example of ClusterConfig object enabling gitops Flux v2
# in a cluster:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-12
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1

gitops:
  flux:
    gitProvider: github             # required. options are github or gitlab
    flags:                          # required. arbitrary map[string]string for all flux args.
      # these args are not controlled by eksctl. see https://fluxcd.io/docs/get-started/ for all available flags
      owner: "daniel.kushner"
      username: "wd.community"
      repository: "my-inf"
      hostname: "https://bitbucket.workday.com"
#      branch: "main"
      password: "G,bt2r65G2"
      namespace: "eks-sample-app"
      token-auth: "NzYyOTY3MTcyOTY0Ovlbwiebennr+TQ1I+0qxAvH0Z5Z"
      path: "mychart"
#  --token-auth --path=clusters/my-cluster

#  flux bootstrap bitbucket-server --owner=<project> --username=<user> --repository=<repository name> --branch=main --hostname=<domain> --token-auth --path=clusters/my-cluster

